/*
 * DOCSMOREAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.docsmore.api.controllers;

import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;
import android.test.suitebuilder.annotation.LargeTest;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.docsmore.api.models.*;
import com.docsmore.api.exceptions.*;
import com.docsmore.api.APIHelper;
import com.docsmore.api.Configuration;
import com.docsmore.api.testing.TestHelper;
import com.docsmore.api.controllers.GetAnAccessTokenController;
import com.docsmore.api.controllers.syncwrapper.APICallBackCatcher;

import com.fasterxml.jackson.core.type.TypeReference;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class GetAnAccessTokenControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static GetAnAccessTokenController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        Configuration.initialize(InstrumentationRegistry.getContext());
        controller = getClient().getGetAnAccessToken();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Make sure you call this in server side code. Exposing apiKey and clientSecret is a not a good idea on front end.
     * @throws Throwable
     */
    @Test
    public void testGetAuthTOKEN11() throws Throwable {
        // Parameters for the API call
        GetAuthTOKENRequest body = APIHelper.deserialize("{    \"apiKey\": \"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\",    \"clientSecret\": \"XXXXXXXXXXXXX\"}", new TypeReference<GetAuthTOKENRequest>(){});

        // Set callback and perform API call
        GetAuthTOKENResponse result = null;
        APICallBackCatcher<GetAuthTOKENResponse> response = new APICallBackCatcher<GetAuthTOKENResponse>();
        controller.setHttpCallBack(httpResponse);
        controller.createGetAuthTOKENAsync(body, response);
        result = response.getResult();

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", TestHelper.nullString);
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
        assertEquals("Response body does not match exactly",
                "{    \"access_token\": \"eyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"}", 
                TestHelper.convertStreamToString(httpResponse.getResponse().getRawBody()));
    }

}
