/*
 * DOCSMOREAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.docsmore.api;

import com.docsmore.api.controllers.*;
import com.docsmore.api.http.client.HttpClient;

public class DOCSMOREAPIClient {
    /**
     * Singleton access to GetAnAccessToken controller
     * @return	Returns the GetAnAccessTokenController instance 
     */
    public GetAnAccessTokenController getGetAnAccessToken() {
        return GetAnAccessTokenController.getInstance();
    }

    /**
     * Singleton access to DOCUMENTFLOWS controller
     * @return	Returns the DOCUMENTFLOWSController instance 
     */
    public DOCUMENTFLOWSController getDOCUMENTFLOWS() {
        return DOCUMENTFLOWSController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public DOCSMOREAPIClient() {
    }

}