/*
 * DOCSMOREAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.docsmore.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetAuthTOKENRequest 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5730004570373459403L;
    private String apiKey;
    private String clientSecret;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("apiKey")
    public String getApiKey ( ) { 
        return this.apiKey;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("apiKey")
    public void setApiKey (String value) { 
        this.apiKey = value;
        notifyObservers(this.apiKey);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("clientSecret")
    public String getClientSecret ( ) { 
        return this.clientSecret;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("clientSecret")
    public void setClientSecret (String value) { 
        this.clientSecret = value;
        notifyObservers(this.clientSecret);
    }
 
}
 